name: tech_lingual_quest
description: A gamified learning app for improving technical English skills

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core dependencies for the app
  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.6.1

  # Database
  sqflite: ^2.4.1
  path: ^1.9.0

  # Routing
  go_router: ^12.1.3

  # Environment configuration
  flutter_dotenv: ^5.2.1

  # Logging
  logger: ^2.6.0

  # JSON serialization
  json_annotation: ^4.9.0

  # Localization and preferences
  shared_preferences: ^2.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules
  flutter_lints: ^3.0.0

  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.9.0
  
  # Test dependencies for database testing on desktop
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true

  # Internationalization configuration
  generate: true

  # Assets
  assets:
    - assets/images/
    - assets/translations/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
